src/main/java/edu/iit/sat/itmd4515/pnaika/fp/bean/EmployeeUpdateBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.iit.sat.itmd4515.pnaika.fp.bean;

import edu.iit.sat.itmd4515.pnaika.fp.domain.Address;
import edu.iit.sat.itmd4515.pnaika.fp.domain.Employee;
import edu.iit.sat.itmd4515.pnaika.fp.domain.security.Group;
import edu.iit.sat.itmd4515.pnaika.fp.domain.security.User;
import edu.iit.sat.itmd4515.pnaika.fp.ejb.AddressService;
import edu.iit.sat.itmd4515.pnaika.fp.ejb.EmployeeService;
import edu.iit.sat.itmd4515.pnaika.fp.ejb.UserService;
import edu.iit.sat.itmd4515.pnaika.fp.web.AbstractJSFBean;
import edu.iit.sat.itmd4515.pnaika.fp.web.LoginBean;
import java.text.ParseException;
import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.enterprise.context.RequestScoped;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.faces.context.Flash;
import javax.inject.Inject;
import javax.inject.Named;

/**
 *
 * @author Prashanth
 */

@Named(value = "employeeUpdateBean")
@RequestScoped
public class EmployeeUpdateBean extends AbstractJSFBean{
    
    @EJB
    private UserService userService;
    
    @EJB
    private EmployeeService employeeService;
    
    @EJB
    private AddressService addressService;
    
    @Inject
    private LoginBean loginBean;
    
    private Employee employee;
    private Address address;
    private User user;

    public EmployeeUpdateBean() {
        super.postContructor();
    }

    @PostConstruct
    private void postConstruct() {
        super.postContructor();
        employee = new Employee();
        employee.setAddress(new Address());
        employee.setUser(new User());
        employee = employeeService.findByUsername(loginBean.getRemoteUser());   
    }
    
    public String saveEmployee() throws ParseException{
        
        User userName = userService.find(employee.getUser().getUserName());
        
        if(userName != null){
            facesContext.addMessage(null, new FacesMessage("User Name   " +employee.getUser().getUserName() +" is already present!"));
            return "/employeePortal/updateProfile.xhtml";   
        }else{
            Group g1 = new Group("Employees", "Group of Employees");
            user = new User(employee.getUser().getUserName(), employee.getUser().getPassword());
            
            user.addGroup(g1);
            userService.update(user);
            
            employeeService.update(employee);
            addressService.update(employee.getAddress());
            facesContext.addMessage(null, new FacesMessage("Employee updation is complete !!!, Thank you."));
        }
        return "/employeePortal/welcome.xhtml";
    }

    public AddressService getAddressService() {
        return addressService;
    }

    public void setAddressService(AddressService addressService) {
        this.addressService = addressService;
    }

    public LoginBean getLoginBean() {
        return loginBean;
    }

    public void setLoginBean(LoginBean loginBean) {
        this.loginBean = loginBean;
    }

    public Address getAddress() {
        return address;
    }

    public void setAddress(Address address) {
        this.address = address;
    }

    public FacesContext getFacesContext() {
        return facesContext;
    }

    public void setFacesContext(FacesContext facesContext) {
        this.facesContext = facesContext;
    }

    public Flash getFlash() {
        return flash;
    }

    public void setFlash(Flash flash) {
        this.flash = flash;
    }

    public UserService getUserService() {
        return userService;
    }

    public void setUserService(UserService userService) {
        this.userService = userService;
    }

    public EmployeeService getEmployeeService() {
        return employeeService;
    }

    public void setEmployeeService(EmployeeService employeeService) {
        this.employeeService = employeeService;
    }

    public Employee getEmployee() {
        return employee;
    }

    public void setEmployee(Employee employee) {
        this.employee = employee;
    }

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }
    
    
}

src/main/java/edu/iit/sat/itmd4515/pnaika/fp/domain/Employee.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.iit.sat.itmd4515.pnaika.fp.domain;

import edu.iit.sat.itmd4515.pnaika.fp.domain.security.User;
import java.io.Serializable;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToOne;
import javax.persistence.PrePersist;
import javax.persistence.PreUpdate;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 *
 * @author Prashanth
 */

@Entity
@NamedQueries({
    @NamedQuery(name = "Employee.findByName",query = "select e from Employee e where e.emp_name = :emp_name"),
    @NamedQuery(name = "Employee.findById",query = "select e from Employee e where e.emp_id = :emp_id"),
    @NamedQuery(name = "Employee.findAll",query = "select e from Employee e"),
    @NamedQuery(name = "Employee.findByUsername",query = "select e from Employee e where e.user.userName = :username"),
})
public class Employee implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE)
    private Long emp_id;
    
    @OneToOne
    private User user;

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    @OneToOne
    @JoinColumn(name="ADDRESS_ID")
    private Address address;
    
    private String emp_name;    
    private String emp_phone;    
    private String emp_email;
    
    @Temporal(TemporalType.TIMESTAMP)
    private Date EmpLastUpdated;

    public Date getEmpLastUpdated() {
        return EmpLastUpdated;
    }

    @PreUpdate
    @PrePersist   
    public void setEmpLastUpdated() {
        EmpLastUpdated = GregorianCalendar.getInstance().getTime();
    }


    public Employee() {
    }

    
    public String getEmp_email() {
        return emp_email;
    }

    public void setEmp_email(String emp_email) {
        this.emp_email = emp_email;
    }

    public String getEmp_phone() {
        return emp_phone;
    }

    public void setEmp_phone(String emp_phone) {
        this.emp_phone = emp_phone;
    }

    public String getEmp_name() {
        return emp_name;
    }

    public void setEmp_name(String emp_name) {
        this.emp_name = emp_name;
    }

    public Long getEmp_id() {
        return emp_id;
    }

    public void setEmp_id(Long emp_id) {
        this.emp_id = emp_id;
    }

    public Address getAddress() {
        return address;
    }

    public void setAddress(Address address) {
        this.address = address;
    }

    public void setEmpLastUpdated(Date EmpLastUpdated) {
        this.EmpLastUpdated = EmpLastUpdated;
    }

    public Employee(String emp_name, String emp_phone, String emp_email) {
        this.emp_name = emp_name;
        this.emp_phone = emp_phone;
        this.emp_email = emp_email;
    }
        
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder(super.toString());
        sb.append("\n");
        sb.append("------------------------------------------------------");
        sb.append("\n");
        sb.append("Employee Id :").append(emp_id).append("\n");
        sb.append("Employee Name :").append(emp_name).append("\n");
        sb.append("Employee email :").append(emp_email).append("\n");
        sb.append("------------------------------------------------------"+"\n");
        return sb.toString();
    }
}

src/main/webapp/resources/ezcomp/billingDetails.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:cc="http://xmlns.jcp.org/jsf/composite"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">

    <!-- INTERFACE -->
    <cc:interface>
        <cc:attribute name ="BillingDetails" required="true"/>
        <cc:attribute name = "EmpController" required="false"/>
    </cc:interface>

    <!-- IMPLEMENTATION -->
    <cc:implementation>
        
        <h:panelGroup rendered="#{not facesContext.validationFailed and not empty facesContext.messageList}" layout="block" class="alert alert-warning alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                    <h:messages style="color:red" layout="table" globalOnly="false" showSummary="true" showDetail="false"/>
        </h:panelGroup>
        
        <h:dataTable style="font-size: small"  rendered="#{not empty cc.attrs.BillingDetails}" class="table table-hover table-striped " value ="#{cc.attrs.BillingDetails}" var = "bill">
            <h:column>
                <f:facet name ="header">      
                    <h:outputText value ="Billing ID"/>
                </f:facet>
                <h:outputText value ="#{bill.getBilling_id()}"/>
            </h:column>
            
            <h:column>
                <f:facet name ="header">      
                    <h:outputText value ="Customer Name"/>
                </f:facet>
                <h:outputText value ="#{bill.getCustomer().getCust_name()}"/>
            </h:column>
            
            <h:column>
                <f:facet name ="header">      
                    <h:outputText value ="Customer Phone No."/>
                </f:facet>
                <h:outputText value ="#{bill.getCustomer().getCust_phone()}"/>
            </h:column>
            
            <h:column>
                <f:facet name ="header">      
                    <h:outputText value ="Customer Email"/>
                </f:facet>
                <h:outputText value ="#{bill.getCustomer().getCust_email()}"/>
            </h:column>
            
            <h:column>
                <f:facet name ="header">      
                    <h:outputText value ="Parking Cost"/>
                </f:facet>
                <h:outputText value ="#{bill.getParking().getParking_amount()}"/>
            </h:column>
            
            <h:column>
                <f:facet name ="header">      
                    <h:outputText value ="Parking Hours"/>
                </f:facet>
                <h:outputText value ="#{bill.getParking().getParking_hours()}"/>
            </h:column>
            
            <h:column>
                <f:facet name ="header">      
                    <h:outputText value ="Slot Name"/>
                </f:facet>
                <h:outputText value ="#{bill.getParking().getParking_slotname()}"/>
            </h:column>
            
            <h:column>
                <f:facet name ="header">      
                    <h:outputText value ="Vehicle Type"/>
                </f:facet>
                <h:outputText value ="#{bill.getVehicle().getVehicle_type()}"/>
            </h:column>
            
            <h:column>
                <f:facet name ="header">      
                    <h:outputText value ="Payment Type"/>
                </f:facet>
                <h:outputText value ="#{bill.getPayment().getPayment_type()}"/>
            </h:column>
            
            <h:column>
                <f:facet name ="header">      
                    <h:outputText value ="Parking Date"/>
                </f:facet>
                <h:outputText  value ="#{bill.getParking().getParking_date()}">
                    <f:convertDateTime type="date" dateStyle="default"/>
                </h:outputText>    
            </h:column>
            
            <h:column>
                <f:facet name ="header">      
                    <h:outputText value ="Parking Time"/>
                </f:facet>
                <h:outputText  value ="#{bill.getParking().getParking_date()}">
                    <f:convertDateTime type="time" dateStyle="default"/>
                </h:outputText>    
            </h:column>

        </h:dataTable>
        
        <h:outputLabel rendered="#{empty cc.attrs.BillingDetails}" value="Customer Details not available"></h:outputLabel>


    </cc:implementation>
</html>

src/main/webapp/resources/ezcomp/custProfile.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:cc="http://xmlns.jcp.org/jsf/composite"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      template="./../WEB-INF/portalTemplate.xhtml"
      xmlns:p="http://xmlns.jcp.org/jsf/passthrough">

    <!-- INTERFACE -->
    <cc:interface>
        <cc:attribute name="customer" required="true" type="edu.iit.sat.itmd4515.pnaika.fp.domain.Customer"/>
        <cc:attribute name="readonly" type="java.lang.Boolean" required="false" default="true" />
        <cc:attribute name="action" required="false" method-signature="java.lang.String action()"/>
    </cc:interface>

    <!-- IMPLEMENTATION -->
    <cc:implementation>
        
    <h:panelGroup rendered="#{not facesContext.validationFailed and not empty facesContext.messageList}" layout="block" class="alert alert-warning alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                    <h:messages style="color:red" layout="table" globalOnly="false" showSummary="true" showDetail="false"/>
    </h:panelGroup>    
    
    <h:form>
        <table class="table-responsive" id="SIform">           
            <tr>
                <tr>
                <td height="35px">
                    <h:outputLabel title="UserName" for="username" value ="UserName" />
                </td>
                <td height="35px">
                    <h:inputText class="form-control" p:placeholder="User Name" id ="username" requiredMessage="User Name is mandatory" value ="#{cc.attrs.customer.user.userName}" required="true" validatorMessage="UserName is Mandatory"/>                       
                    <h:messages  for="username" style="color:red"/>
                </td>
                </tr>
                <tr>
                <td height="35px">
                    <h:outputLabel title="Password" for="password" value ="Password" />
                </td>
                <td height="35px">
                    <h:inputSecret class="form-control" id ="password" requiredMessage="Password is mandatory" value ="#{cc.attrs.customer.user.password}" p:placeholder="Password" required="true" validatorMessage="Password is Mandatory"/>                       
                    <h:messages  for="password" style="color:red"/>
                </td>
                </tr>
                
       
                <tr>
                <td height="35px">
                <h:outputLabel title="Customer Name" for="custname" value ="Customer Name" />
                </td>
                <td height="35px">    
                <h:inputText p:placeholder="Full Name" class="form-control"  required="true" requiredMessage="Please enter Customer Name" id="custname" value="#{cc.attrs.customer.cust_name}" validatorMessage="No special characters allowed other than '.' and ',' ">                                                                   
                    <f:validateRegex pattern="[A-Za-z .,]+"/>  
                </h:inputText>            
                <h:messages  for="custname" style="color:red"/>
                </td>
                </tr>    
                
                <tr>
                <td height="35px">
                <h:outputLabel title="Contact Number" for="phone" value="Contact Number" />
                </td>
                <td height="35px">
                    <h:inputText p:placeholder="Phone No." required="true" maxlength="10" requiredMessage="Phone number is mandatory" converterMessage="Please enter valid phone number"  class="form-control" id ="phone" value ="#{cc.attrs.customer.cust_phone}" validatorMessage="Phone number should be number and  10 digits length">            
                    <f:validateRegex pattern="^[0-9]+"/>
                </h:inputText>
                <h:messages  for="phone" style="color:red"/>
                </td>
                </tr> 
                
                <tr>
                <td height="35px">
                <h:outputLabel title="Email" for="Email" value="Email"   />
                </td>
                <td height="35px">
                <h:inputText p:placeholder="email" class="form-control" id ="Email" value ="#{cc.attrs.customer.cust_email}" required="true" requiredMessage="Please enter customer email address" validatorMessage="Student email not in the valid format">
                    <f:validateRegex pattern="^[^@]+@[^@]+\.[^@]+$"/>  
                </h:inputText>
                <h:messages  for="Email" style="color:red"/>
                </td>
                </tr>
                
                <tr>
                <td height="35px">
                <h:outputLabel title="City" for="city" value="City"   />
                </td>
                <td height="35px">
                    <h:inputText p:placeholder="City" class="form-control" id ="city" value ="#{cc.attrs.customer.address.address_city}" required="true" requiredMessage="Please enter customer city" validatorMessage="Valid city name">  
                </h:inputText>
                <h:messages  for="city" style="color:red"/>
                </td>
                </tr>
            
                <tr>
                <td height="35px">
                <h:outputLabel title="State" for="state" value="State"   />
                </td>
                <td height="35px">
                    <h:inputText p:placeholder="State" class="form-control" id ="state" value ="#{cc.attrs.customer.address.address_state}" required="true" requiredMessage="Please enter customer State" validatorMessage="Valid STate name is required">  
                </h:inputText>
                <h:messages  for="state" style="color:red"/>
                </td>
                </tr>
            
                <tr>
                <td height="35px">
                <h:outputLabel title="zip" for="zip" value="Zip Code"   />
                </td>
                <td height="35px">
                    <h:inputText p:placeholder="Zip Code"  class="form-control" id ="zip" value ="#{cc.attrs.customer.address.address_zip}" required="true" requiredMessage="Please enter customer zip code">  
                </h:inputText>
                <h:messages  for="zip" style="color:red"/>
                </td>
                </tr>
            </tr>
        </table>
        <ui:fragment rendered="#{not cc.attrs.readonly}">
                <div class="form-group">
                        <h:commandButton action="#{cc.attrs.action}" class="button expand" value="Save"/>
                </div>
        </ui:fragment>
    </h:form>
    </cc:implementation>
</html>

src/main/webapp/resources/ezcomp/customerDetails.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:cc="http://xmlns.jcp.org/jsf/composite"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:p="http://xmlns.jcp.org/jsf/passthrough">

    <!-- INTERFACE -->
    <cc:interface>
        <cc:attribute name ="CustomerDetails" required="true"/>
        <cc:attribute name = "EmpController" required="false"/>
    </cc:interface>

    <!-- IMPLEMENTATION -->
    <cc:implementation>
        <h:form>
            <table class="table-striped" style="font-size: medium">
                <tr>
                    <td>
                        <h:outputText value ="Enter Customer ID"/>
                    </td>
                    <td> 
                        <h:inputText p:placeholder="Enter Customer ID" class="form-control"  maxlength="4" validatorMessage="Please enter a valid Customer ID" id ="searchboxid" value="#{employeeBean.searchtext}">
                            <f:validateRegex pattern="^[1-9]+"/> 
                        </h:inputText>
                    </td>
                    <td><h:commandButton action ="#{employeeBean.Search()}" value ="Search"/></td>
                </tr>
                <tr>
                    <td colspan="2">
                        <h:messages  for="searchboxid" style="color:red" />
                    </td>
                </tr>
            </table>
        </h:form>
        
        
        <h:dataTable style="font-size: small"  rendered="#{not empty cc.attrs.CustomerDetails}" class="table table-hover table-striped " value ="#{cc.attrs.CustomerDetails}" var = "std">
            <h:column>
                <f:facet name ="header">      
                    <h:outputText value ="Customer ID"/>
                </f:facet>
                <h:outputText value ="#{std.getCust_id()}"/>
            </h:column>

            <h:column>
                <f:facet name ="header">      
                    <h:outputText value ="Customer Name"/>
                </f:facet>
                <h:outputText value ="#{std.getCust_name()}"/>
            </h:column> 

            <h:column>
                <f:facet name ="header">      
                    <h:outputText value ="Email ID"/>
                </f:facet>
                <h:outputText value ="#{std.getCust_email()}"/>
            </h:column>

            <h:column>
                <f:facet name ="header">      
                    <h:outputText value ="Contact Number"/>
                </f:facet>
                <h:outputText value ="#{std.getCust_phone()}"/>
            </h:column>
            
            <h:column>
                <f:facet name ="header">      
                    <h:outputText value ="City"/>
                </f:facet>
                <h:outputText value ="#{std.getAddress().getAddress_city()}"/>
            </h:column>        
            
            <h:column>
                <f:facet name ="header">      
                    <h:outputText value ="State"/>
                </f:facet>
                <h:outputText value ="#{std.getAddress().getAddress_state()}"/>
            </h:column>
            
            <h:column>
                <f:facet name ="header">      
                    <h:outputText value ="Zip Code"/>
                </f:facet>
                <h:outputText value ="#{std.getAddress().getAddress_zip()}"/>
            </h:column>
            
            <h:column>
                <f:facet name ="header">      
                    <h:outputText value ="Last Update Date"/>
                </f:facet>
                <h:outputText value ="#{std.getCustLastUpdate()}">
                    <f:convertDateTime type="date" dateStyle="default"/>
                </h:outputText>
            </h:column>
            
            <h:column>
                <f:facet name ="header">      
                    <h:outputText value ="Last Update Time"/>
                </f:facet>
                <h:outputText value ="#{std.getCustLastUpdate()}">
                    <f:convertDateTime type="time" dateStyle="default"/>
                </h:outputText>
            </h:column>
            
            <h:column>
            <h:form>
                <h:commandLink action ="#{employeeBean.selectCustomer(std)}" value ="Update Information"/>
            </h:form>
            </h:column>
            
            <h:column>
            <h:form>
                <h:commandLink action ="#{employeeBean.deleteCustomer(std)}" value ="Delete this Customer"/>
            </h:form>
            </h:column>
            
            
        </h:dataTable>
        
        <h:outputLabel rendered="#{empty cc.attrs.CustomerDetails}" value="Customer Details not available"></h:outputLabel>


    </cc:implementation>
</html>

src/main/webapp/resources/ezcomp/employeeUpdate.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:cc="http://xmlns.jcp.org/jsf/composite"
      template="./../WEB-INF/portalTemplate.xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://xmlns.jcp.org/jsf/passthrough">

    <!-- INTERFACE -->
    <cc:interface>
        <cc:attribute name="employee" type="edu.iit.sat.itmd4515.pnaika.fp.domain.Employee" required="true" />
        <cc:attribute name="readonly" type="java.lang.Boolean" required="false" default="true" />
        <cc:attribute name="action" required="false" method-signature="java.lang.String action()"/>
    </cc:interface>

    <!-- IMPLEMENTATION -->
    <cc:implementation>
        <h:form>
            <div class="form-group">
                    <h:outputLabel for="id" value="Emp ID  :#{cc.attrs.employee.emp_id}" />
                    <h:inputHidden id="id" value="#{cc.attrs.employee.emp_id}" />
            </div>
            <div class="form-group">
                    <h:outputLabel for="firstName" value="Employee Name" />
                    <h:inputText p:placeholder="First Name :" id="firstName" value="#{cc.attrs.employee.emp_name}" />
            </div>
            <div class="form-group">
                    <h:outputLabel for="LastUpdate" value="Last Update" />
                    <h:inputText p:placeholder="Last Update  :" id="LastUpdate" value="#{cc.attrs.employee.empLastUpdated}">
                        <f:convertDateTime type="date" dateStyle="short"/>
                    </h:inputText>
            </div>
            <ui:fragment rendered="#{not cc.attrs.readonly}">
                <div class="form-group">
                        <h:commandButton action="#{cc.attrs.action}" class="button expand" value="Save"/>
                </div>
            </ui:fragment>
        </h:form>
    </cc:implementation>
</html>

src/main/webapp/resources/ezcomp/emps.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:cc="http://xmlns.jcp.org/jsf/composite"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      template="./../WEB-INF/portalTemplate.xhtml">

    <!-- INTERFACE -->
    <cc:interface>
        <cc:attribute name="employees" required="true"/>
    </cc:interface>

    <!-- IMPLEMENTATION -->
    <cc:implementation>
        <h:dataTable class="table table-hover table-striped " value="#{cc.attrs.employees}" var="employee">
            <h:column>
                <f:facet name="header"><h:outputText value="ID"/></f:facet>
                <h:outputText value="#{employee.emp_id}"/>
            </h:column>
            
            <h:column>
                <f:facet name="header"><h:outputText value="Name"/></f:facet>
                <h:outputText value="#{employee.emp_name}"/>
            </h:column>
            
            <h:column>
                <f:facet name="header"><h:outputText value="email ID"/></f:facet>
                <h:outputText value="#{employee.emp_email}"/>
            </h:column>
            
            <h:column>
                <f:facet name="header"><h:outputText value="Contact No."/></f:facet>
                <h:outputText value="#{employee.emp_phone}"/>
            </h:column>
            
            <h:column>
                <f:facet name ="header">      
                    <h:outputText value ="City"/>
                </f:facet>
                <h:outputText value ="#{employee.getAddress().getAddress_city()}"/>
            </h:column>        
            
            <h:column>
                <f:facet name ="header">      
                    <h:outputText value ="State"/>
                </f:facet>
                <h:outputText value ="#{employee.getAddress().getAddress_state()}"/>
            </h:column>
            
            <h:column>
                <f:facet name ="header">      
                    <h:outputText value ="Zip Code"/>
                </f:facet>
                <h:outputText value ="#{employee.getAddress().getAddress_zip()}"/>
            </h:column>
            
            <h:column>
                <f:facet name="header"><h:outputText value="Last Updated Date"/></f:facet>
                <h:outputText value="#{employee.empLastUpdated}">
                    <f:convertDateTime type="date" dateStyle="default" timeStyle="full"/>
                </h:outputText>
            </h:column>
            
            <h:column>
                <f:facet name="header"><h:outputText value="Last Updated Time"/></f:facet>
                <h:outputText value="#{employee.empLastUpdated}">
                    <f:convertDateTime type="time" dateStyle="default" timeStyle="full"/>
                </h:outputText>
            </h:column>
            
        </h:dataTable>
    </cc:implementation>
</html>