src/main/java/edu/iit/sat/itmd4515/pnaika/fp/web/CustomerPortalServlet.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.iit.sat.itmd4515.pnaika.fp.web;


import edu.iit.sat.itmd4515.pnaika.fp.domain.Address;
import edu.iit.sat.itmd4515.pnaika.fp.domain.Customer;
import edu.iit.sat.itmd4515.pnaika.fp.ejb.AddressService;
import edu.iit.sat.itmd4515.pnaika.fp.ejb.CustomerService;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.List;
import javax.ejb.EJB;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

/**
 *
 * @author Prashanth
 */

@WebServlet(name = "CustomerPortalServlet", urlPatterns = {"/customerPortal",
                                                           "/customerPortal/",
                                                           "/readCustomer"})
public class CustomerPortalServlet extends HttpServlet {

    @EJB
    private CustomerService customerService;
    
    @EJB
    private AddressService addressService;
    
    /**
     * Processes requests for both HTTP <code>GET</code> and <code>POST</code>
     * methods.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    protected void processRequest(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        response.setContentType("text/html;charset=UTF-8");
        try (PrintWriter out = response.getWriter()) {
            /* TODO output your page here. You may use following sample code. */
//            out.println("<!DOCTYPE html>");
//            out.println("<html>");
//            out.println("<head>");
//            out.println("<title>Customer Portal</title>");            
//            out.println("<style>"
//                         +"header{\n" +
//                        "text-align: left;\n" +
//                        "font-family: 'Lora', serif;\n" +
//                        "width: auto;\n" +
//                        "height:auto;\n" +
//                        "font-size: 25px;\n" +
//                        "padding: 0 15px 0 15px;\n" +
//                        "border-color: black;\n" +
//                        
//                        "}"
//                    +"*{"+
//                         "box-sizing: border-box;"+
//                    "}"
//                    +".table{"+
//                        "margin:15px;"+
//                    "}"+
//                    
//                    "thead{\n" +
//                        "font-weight: bold;" +
//                    "}"
//                    +"h3{"+
//                        "margin:10px;"+
//                    "}"
//                    + "</style>");
//            
//            out.println("</head>");
//            out.println("<body>");
//            
//            
//            if (request.isUserInRole("customer")) {                
//                Customer c = customerService.findByUsername(request.getRemoteUser());
//                out.println("<br>");
//                out.println("<header> Hi " + c.getCust_name() +", Please find your details.</header>");
//                out.println("<br>");
//                out.println("<br>");
//                out.println("<hr>");
//                out.println("<br>");
//                Address a = addressService.find(c.getAddress().getAddress_id());
//                
//                out.println("<table class='table'> <thead><tr> <td width ='50'>"
//                             + "ID" + "</td> <td width='150'> "
//                             + "Customer Name"+"</td> <td width='100'> "
//                             + "Contact no"+"</td> <td width='200'> "
//                             + "Customer Email ID"+" </td> <td width ='100'>  "
//                             + "City"+"</td> <td width ='100'> "
//                             + "State"+" </td> <td width ='100'> "
//                             + "Zip Code"+" </td> <td width ='100'> "
//                             + "Address Type"+" </td>  "
//                             +"</tr></thead></table>");
//                out.println("<table class='table table-hover'> <tbody><tr> <td width ='50'>"
//                             + c.getCust_id() + "</td> <td width='150'> "
//                             + c.getCust_name()+"</td> <td width='100'> "
//                             + c.getCust_phone()+"</td> <td width='200'> "
//                             + c.getCust_email()+" </td> <td width ='100'> "
//                             + a.getAddress_city()+"</td> <td width ='100'> "
//                             + a.getAddress_state()+"</td> <td width ='100'> "
//                             + a.getAddress_zip()+"</td> <td width ='100'> "
//                             + a.getAddress_type()+"</td> "
//                             +"</tr></tbody></table>");
//                out.println("<br>");
//                out.println("<br>");
//            }
//            
//            out.println("<a href=\"" + request.getContextPath() + "/logout\">Logout</a>"+"\n");
//            out.println("<br>");
//            out.println("<br>");
//            out.println("<a href=\"/pnaika-fp/site/apidocs/index.html\"><strong>Please click here to see <u> JAVA DOC</u></strong></a>");
//            out.println("</body>");
//            out.println("</html>");
        }
    }

    // <editor-fold defaultstate="collapsed" desc="HttpServlet methods. Click on the + sign on the left to edit the code.">
    /**
     * Handles the HTTP <code>GET</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        
                processRequest(request, response);
//        switch(request.getServletPath()){
//            case "/readCustomer" :
//                    
//                request.setAttribute("customer", customerService.findAll());
//                request.getRequestDispatcher("/WEB-INF/pages/readCustomer.jsp").forward(request, response);
//                break;
//        }
    }

    /**
     * Handles the HTTP <code>POST</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        processRequest(request, response);
    }

    /**
     * Returns a short description of the servlet.
     *
     * @return a String containing servlet description
     */
    @Override
    public String getServletInfo() {
        return "Short description";
    }// </editor-fold>

}

src/main/java/edu/iit/sat/itmd4515/pnaika/fp/web/LoginBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.iit.sat.itmd4515.pnaika.fp.web;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.annotation.PostConstruct;
import javax.enterprise.context.RequestScoped;
import javax.faces.application.FacesMessage;
import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;
import javax.inject.Named;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import static javax.swing.text.StyleConstants.Size;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 *
 * @author Prashanth
 */

@Named
@RequestScoped
public class LoginBean extends AbstractJSFBean{

    private static final Logger LOG = Logger.getLogger(LoginBean.class.getName());
    
    @NotNull(message = "Please enter Username!")
    private String username; 
    
    @NotNull(message = "Please enter password!")
    @Size(min = 8, message = "Password must be at least 8 characters in length.")
    private String password;

    public LoginBean() {
    }
    
    @PostConstruct
    private void postConstruct(){
        super.postContructor();
    }
    public boolean isCustomer() {
        return facesContext.getExternalContext().isUserInRole("customer");
    }
    
    public boolean isEmployee() {
        return facesContext.getExternalContext().isUserInRole("employee");
    }
    
    public String getPortalPathByRole(String path) {
        if (isCustomer()) {
            return "/customerPortal" + path;
        } else if (isEmployee()) {
            return "/employeePortal" + path;
        } else {
            return path;
        }
    }   

    public String doLogin(){
        HttpServletRequest req = (HttpServletRequest) facesContext.getExternalContext().getRequest();
        try {
            req.login(username, password);
        } catch (ServletException ex) {
            LOG.log(Level.SEVERE, null, ex);
            facesContext.addMessage(null, new FacesMessage("Bad Login", "Detail: You made a bad login!"));
            return "/login.xhtml";
        }
        return getPortalPathByRole("/welcome.xhtml");
    }
    
    public String getRemoteUser(){
        return facesContext.getExternalContext().getRemoteUser();
    }
    
    public String doLogout(){
        HttpServletRequest req = (HttpServletRequest) facesContext.getExternalContext().getRequest();
        try {
            req.logout();
        } catch (ServletException ex) {
            LOG.log(Level.SEVERE, null, ex);
            facesContext.addMessage(null, new FacesMessage("Bad Logout", "Detail: You made a bad login!"));
            return "/login.xhtml";
        }
        return "/login.xhtml";
    }
    
    public void checklogedin() throws IOException {
        LOG.log(Level.INFO, "checklogedin");
        String sUser = getRemoteUser();

        LOG.log(Level.INFO, "checklogedin{0}", sUser);
        if (sUser == null) {
            // return null;
        } else {
            ExternalContext context = FacesContext.getCurrentInstance().getExternalContext();
            context.redirect(context.getRequestContextPath() + getPortalPathByRole("/welcome.xhtml"));
        }
    }
    
    public String getUsername() {
        return username;
    }
    public void setUsername(String username) {
        this.username = username;
    }
    
    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }


}

src/main/webapp/customerPortal/oldReservation.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                template="./../WEB-INF/portalTemplate.xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:define name="title">
        Customer Billing History
    </ui:define>
    
    <ui:define name="heading">
        <div  class="page-header" style="color: #d9534f;background-color: wheat">
            Reservation History of #{loginBean.remoteUser.toUpperCase()}
        </div>
    </ui:define>
    <ui:define name="body">
        <div align="right" style = " vertical-align: top; display: block;padding-right: 5%">
            <a  href = "../index.xhtml">Main Menu </a> |
            <a href="welcome.xhtml">Go Back!</a>
        </div>
        
        <h:panelGroup rendered="#{not facesContext.validationFailed and not empty facesContext.messageList}" layout="block" class="alert alert-warning alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                    <h:messages style="color:red" layout="table" globalOnly="false" showSummary="true" showDetail="false"/>
        </h:panelGroup>
        
        <br/>
        <h:dataTable border="3" width="100%" style="alignment-adjust: central" value="#{customerService.findByUsername(loginBean.remoteUser)}" var="customer">         
            <h:column>
                <f:facet name="header"><h:outputText value="Customer ID"/></f:facet>
                <h:outputText value="#{customer.cust_id}"/>
            </h:column>
            <h:column>
                <f:facet name="header"><h:outputText value="Customer Name"/></f:facet>
                <h:outputText value="#{customer.cust_name}"/>
            </h:column>
            <h:column>
                <h:dataTable border="1" width="100%" value="#{billingService.findCustId(customer.cust_id)}" var="billDetails">
                    <h:column>
                        <f:facet name="header"><h:outputText value="BillingID"/></f:facet>
                        <h:outputText value="#{billDetails.billing_id}"/>
                    </h:column>
                    <h:column>
                        <f:facet name="header"><h:outputText value="Billing Date"/></f:facet>
                        <h:outputText value="#{billDetails.bill_date}"/>
                    </h:column>
                </h:dataTable>
            </h:column>
            <h:column>
                <h:dataTable border="1" width="100%" value="#{parkingService.findCustId(customer.cust_id)}" var="parkDetails">
                    <h:column>
                        <f:facet name="header"><h:outputText value="Parking Date"/></f:facet>
                        <h:outputText value="#{parkDetails.parking_date}"/>
                    </h:column>
                    <h:column>
                        <f:facet name="header"><h:outputText value="Parking Charges"/></f:facet>
                        <h:outputText value="#{parkDetails.parking_amount}"/>
                    </h:column>
                    <h:column>
                        <f:facet name="header"><h:outputText value="Hours Parked"/></f:facet>
                        <h:outputText value="#{parkDetails.parking_hours}"/>
                    </h:column>
                    <h:column>
                        <f:facet name="header"><h:outputText value="Parking Slot Name"/></f:facet>
                        <h:outputText value="#{parkDetails.parking_slotname}"/>
                    </h:column>
                </h:dataTable>
            </h:column>
        </h:dataTable>            
        <br/>
        
        <hr/>
        <h:form><h:commandLink action="#{loginBean.doLogout()}" value="Logout"/></h:form>
    </ui:define>

</ui:composition>

src/main/webapp/customerPortal/reserve.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                template="./../WEB-INF/portalTemplate.xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:p="http://xmlns.jcp.org/jsf/passthrough"
                >
                    

    <ui:define name="title">
        RESERVE A SITE !
    </ui:define>

    <ui:define name="heading">
        <div  class="page-header" style="color: #d9534f;background-color: wheat">
            #{loginBean.remoteUser.toUpperCase()} ,Please Complete the below form and Submit! 
        </div>
    </ui:define>
    
    <ui:define name="body">
        
        <div align="right" style = " vertical-align: top; display: block;padding-right: 5%">
            <a  href = "../index.xhtml">Main Menu </a> |
            <a href="welcome.xhtml">Go Back!</a>
        </div>
        
        <h:panelGroup rendered="#{not facesContext.validationFailed and not empty facesContext.messageList}" layout="block" class="alert alert-warning alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                    <h:messages style="color:red" layout="table" globalOnly="false" showSummary="true" showDetail="false"/>
        </h:panelGroup>
                
        <h:outputText rendered="#{empty billingController.billingService.findAll()}">
            No billing Information available!
        </h:outputText>
                
                <div align = "center" style="padding-top: 60px; border: black solid thin;">
                <h:form>
                    <table>
                        <tr>
                            <td height="35px">
                                <h:outputLabel for="parkingHours" value="How many hours you wish to park ? : " />
                            </td>
                            <td height="35px">
                                <h:inputText  class="form-control"  required="true" requiredMessage="Please enter hours in numbers" id="parkingHours" value="#{billingController.parking_hours}" validatorMessage="hours should be in positive number">                                                                   
                                    <f:convertNumber minIntegerDigits="1"/>
                                </h:inputText>
                                
                                <h:messages  for="parkingHours" style="color:red"/>
                            </td>
                        </tr> 
                        <tr>
                            <td height="35px">
                                <h:outputLabel for="name" value="Parking slot name : " />
                            </td>
                            <td height="35px">
                                <h:inputText class="form-control" id ="name" value ="#{billingController.parking_slotname}"  p:placeholder="SlotName Eg.P6" required="true" requiredMessage="Please enter Parking slot name" validatorMessage="Start with 'P' and a number">
                                    <f:validateRegex pattern="[Pp]+[0-9]"/>  
                                </h:inputText>
                                <h:messages  for="name" style="color:red"/>
                            </td>
                        </tr>
                        
                        <tr>
                            <td height="35px">
                                <h:outputLabel for="vehicleType1" value="Select Vehicle Type : " />
                            </td>
                            <td height="35px">
                                <h:selectOneMenu id="vehicleType1" style="width:250px" value="#{billingController.vehicle_type}">
                                    <f:selectItems value="#{vehicleService.findType()}" />
                                </h:selectOneMenu>
                                <h:messages  for="vehicleType1" style="color:red"/>
                            </td>
                        </tr>
                        <tr>
                            <td height="35px">
                                <h:outputLabel for="paymentType" value="Select Payment Type : " />
                            </td>
                            <td height="35px">
                                <h:selectOneMenu id="paymentType" style="width:250px" value="#{billingController.payment_type}">
                                    <f:selectItems value="#{paymentService.findType()}" />
                                </h:selectOneMenu>
                              
                                <h:messages  for="paymentType" style="color:red"/>
                            </td>
                        </tr>
                        <tr>
                        <td height="35px" colspan="2">
                            <h:commandButton value="Submit" action="#{billingController.createNewBill()}"/>
                        </td>   
                        <td>
                            <h:commandButton value="reset" type="reset" />   
                        </td>
                    </tr>
                </table>
            </h:form>
        </div>    
        <br/>
        
        <hr/>
        <h:form><h:commandLink action="#{loginBean.doLogout()}" value="Logout"/></h:form>
    </ui:define>
</ui:composition>

src/main/webapp/customerPortal/updateProfile.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:ezcomp="http://xmlns.jcp.org/jsf/composite/ezcomp">
  
    <ui:composition template="./../WEB-INF/publicTemplate.xhtml">
        <ui:define name="title">
            Customer Profile
        </ui:define>

        <ui:define name="heading">
            <div  class="page-header" style="color: #d9534f;background-color: wheat">
            Please Update the information!
            </div>
        </ui:define>

        <ui:define name="body">
            
            <div align="right" style = " vertical-align: top; display: block;padding-right: 5%">
                <a  href = "../index.xhtml">Main Menu </a> |
                <a href="welcome.xhtml">Go Back!</a>
            </div>

            <hr/>
            <br/>
            <ezcomp:custProfile customer="#{customerBean.customer}"  action="#{customerBean.saveCustomer()}" readonly="false"/>
                        <hr/>
            <h:form><h:commandLink action="#{loginBean.doLogout()}" value="Logout"/></h:form>
        </ui:define>
    </ui:composition>
</html>

src/main/webapp/customerPortal/welcome.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                template="./../WEB-INF/portalTemplate.xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:define name="title">
        Customer Portal
    </ui:define>

    <ui:define name="heading">
         <div  class="page-header" style="color: #d9534f;background-color: wheat">
        Welcome #{loginBean.remoteUser.toUpperCase()}, Please select from the menu below!
         </div>
    </ui:define>
    
    <ui:define name="body">
        
        <h:panelGroup rendered="#{not facesContext.validationFailed and not empty facesContext.messageList}" layout="block" class="alert alert-warning alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                    <h:messages style="color:red" layout="table" globalOnly="false" showSummary="true" showDetail="false"/>
        </h:panelGroup>
        <br/>
        <hr/>
        <table class="table table-striped">
            <tbody>
                <tr>
                    <td>Want to Reserve the site for your vehicle </td><td> <a href="/pnaika-fp/customerPortal/reserve.xhtml">CLICK HERE!</a></td>   
                </tr>
                <tr>
                    <td>Want to See your Reservation? </td><td> <a href="/pnaika-fp/customerPortal/oldReservation.xhtml">CLICK HERE!</a></td>   
                </tr>
                <tr>
                    <td> Do you want to Update your profile ? </td><td> <a href="/pnaika-fp/customerPortal/updateProfile.xhtml">CLICK HERE!</a></td>   
                </tr>
            </tbody>   
        </table>        
        
        <br/>
        
        
        <h:form><h:commandLink action="#{loginBean.doLogout()}" value="Logout"/></h:form>
    </ui:define>

</ui:composition>